# Generated by Django 4.2 on 2023-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plateNumber', models.CharField(max_length=255)),
                ('registrationStatus', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('agencyLocation', models.CharField(max_length=255)),
            ],
        ),
    ]
